@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-down-> "1" MenuList
AddressBook *-down-> "1" OrderList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag
Person "1" <-left-> "*" Order

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

OrderList -down-> Order

Order *--> "*" Product
Order *--> "*" Quantity

MenuList -down-> Product
@enduml
