@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CompleteOrderCommandParser" as CompleteCommandParser LOGIC_COLOR
participant "c:CompleteOrderCommand" as CompleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR
participant ":Storage" as Storage STORAGE_COLOR_T1
end box

[-> LogicManager : execute("complete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("complete 1")
activate AddressBookParser

create CompleteCommandParser
AddressBookParser -> CompleteCommandParser
activate CompleteCommandParser

CompleteCommandParser --> AddressBookParser
deactivate CompleteCommandParser

AddressBookParser -> CompleteCommandParser : parse("1")
activate CompleteCommandParser

create CompleteCommand
CompleteCommandParser -> CompleteCommand
activate CompleteCommand

CompleteCommand --> CompleteCommandParser
deactivate CompleteCommand

CompleteCommandParser --> AddressBookParser : c
deactivate CompleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CompleteCommandParser -[hidden]-> AddressBookParser
destroy CompleteCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> CompleteCommand : execute(m)
activate CompleteCommand

CompleteCommand -> Model : updateCompletedOrder(id)
activate Model

Model --> CompleteCommand
deactivate Model

create CommandResult
CompleteCommand -> CommandResult
activate CommandResult

CommandResult --> CompleteCommand
deactivate CommandResult

CompleteCommand --> LogicManager
deactivate CompleteCommand

create Storage
LogicManager -> Storage
activate Storage

Storage --> LogicManager
deactivate Storage

[<--LogicManager
deactivate LogicManager
@enduml
