@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":StageCommandParser" as StageCommandParser LOGIC_COLOR
participant "s:StageCommand" as StageCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR
participant ":Storage" as Storage STORAGE_COLOR_T1
end box

[-> LogicManager : execute("stage o/1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("stage o/1")
activate AddressBookParser

create StageCommandParser
AddressBookParser -> StageCommandParser
activate StageCommandParser

StageCommandParser --> AddressBookParser
deactivate StageCommandParser

AddressBookParser -> StageCommandParser : parse("o/1")
activate StageCommandParser

create StageCommand
StageCommandParser -> StageCommand
activate StageCommand
StageCommand --> StageCommandParser
deactivate StageCommand



StageCommandParser --> AddressBookParser : s
deactivate StageCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
StageCommandParser -[hidden]-> AddressBookParser
destroy StageCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> StageCommand : execute(m)
activate StageCommand

StageCommand -> Model : getOrder(id)
activate Model
Model --> StageCommand

StageCommand -> Model : goToNextStage(order)
Model --> StageCommand

StageCommand -> Model : setOrder(order, order)
Model --> StageCommand

StageCommand -> Model : updateFilteredOrderList(predicate)
Model --> StageCommand
deactivate Model

create CommandResult
StageCommand -> CommandResult
activate CommandResult

CommandResult --> StageCommand
deactivate CommandResult

StageCommand --> LogicManager
deactivate StageCommand

create Storage
LogicManager -> Storage
activate Storage

Storage --> LogicManager
deactivate Storage

[<--LogicManager
deactivate LogicManager
@enduml